name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/backend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
        working-directory: starter/backend
      - name: Run Lint
        run: pipenv run lint
        working-directory: starter/backend
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd starter/backend
          pip install pipenv
          pipenv install --dev
      - name: Run Tests
        run: |
          cd starter/backend
          pipenv run test
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build --tag mp-backend:latest .
        working-directory: starter/backend

      - name: Run Docker container
        run: docker run -p 5000:5000 --name mp-backend -d mp-backend